version: '3'

services:
  web:
    build: .
    container_name: ipo_data_visualizer
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    command: python visualizer/app.py 